# Items names must be used like they are here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
BlockedMaterials:
- "DIAMOND_SWORD"
- "DIAMOND_AXE"
# Mobs names must be used like they are here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
BlockedMobs:
- "WOLF"